INSERT INTO APP_USER (USERNAME, EMAIL, PASSWORD, ROLE, ENABLED)
VALUES ('admin', 'admin@auction.local', '$2a$10$3euPcmQFCiblsZeEu5s7p.9B9Qdr4RweO5QfMByw6h8fC4Jj9v5M2', 'ADMIN', TRUE);

INSERT INTO APP_USER (USERNAME, EMAIL, PASSWORD, ROLE, ENABLED)
VALUES ('owner', 'owner@auction.local', '$2a$10$3euPcmQFCiblsZeEu5s7p.9B9Qdr4RweO5QfMByw6h8fC4Jj9v5M2', 'OWNER', TRUE);

INSERT INTO APP_USER (USERNAME, EMAIL, PASSWORD, ROLE, ENABLED)
VALUES ('user', 'user@auction.local', '$2a$10$3euPcmQFCiblsZeEu5s7p.9B9Qdr4RweO5QfMByw6h8fC4Jj9v5M2', 'USER', TRUE);
