spring.application.name=auction

spring.datasource.host=${DB_HOST:localhost}
spring.datasource.port=${DB_PORT:3050}
spring.datasource.database=${DB_PATH:${user.dir}/database/auction.fdb}
spring.datasource.url=jdbc:firebirdsql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?encoding=UTF8
spring.datasource.username=${DB_USERNAME:SYSDBA}
spring.datasource.password=${DB_PASSWORD:masterkey}
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.FirebirdDialect

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.mustache.prefix=classpath:/templates/
spring.mustache.suffix=.mustache

spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftlh

server.error.include-message=always