spring.application.name=auction
spring.datasource.url=jdbc:firebirdsql://localhost:3050/C:/basa/auction.fdb?encoding=UTF8
spring.datasource.username=SYSDBA
spring.datasource.password=masterkey
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.FirebirdDialect
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mustache.prefix=classpath:/templates/
spring.mustache.suffix=.mustache
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftlh
server.error.include-message=always
